#!/usr/bin/env python3
"""Cut a CalVer release (#508). Run on the dev machine (git + gh authenticated)
after merging PRs and before ./scripts/deploy.sh on the box:

    python scripts/release.py              # dry-run: show what would happen
    python scripts/release.py --execute    # do it
    python scripts/release.py --version 2026.10.3.1 --execute   # emergency override

Version = YYYY.M.D (no leading zeros); the 2nd and later release on the same
day gets .1, .2, ... What --execute does:
  1. refuses unless the tree is clean, on an up-to-date main, with commits since
     the last tag;
  2. collects the PRs merged into main since the previous tag (via gh);
  3. prepends a dated section to CHANGELOG.md (LF endings);
  4. commits "chore(release): <version>", tags it (annotated), pushes both;
  5. runs `gh release create <version>` with the same notes.
The TrueNAS box has a read-only deploy key, so this is why releases are cut here.
"""
import argparse
import datetime
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = "hooptiej/Constructicon"
ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.md"
CHANGELOG_HEADER = (
    "# Changelog\n\n"
    "Constructicon uses CalVer: `YYYY.M.D`, with `.1`, `.2`, ... for further releases the same day.\n"
    "Sections are generated by `scripts/release.py` from the PRs merged since the previous release.\n\n"
)
TAG_RE = re.compile(r"^(\d{4})\.(\d{1,2})\.(\d{1,2})(?:\.(\d+))?$")
CO_AUTHOR = "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>"


def valid_version(v):
    m = TAG_RE.match(v)
    if not m:
        return False
    # no leading zeros anywhere
    return all(p == str(int(p)) for p in m.groups() if p is not None)


def next_version(tags, today):
    """Pure: the next CalVer given existing tag names and a datetime.date.
    Non-CalVer tags are ignored. First release of a day is YYYY.M.D; repeats are
    YYYY.M.D.1, .2, ... (one past the highest existing suffix that day)."""
    base = f"{today.year}.{today.month}.{today.day}"
    highest = None  # None = no release today; 0 = bare base exists
    for t in tags:
        m = TAG_RE.match(t)
        if not m or not valid_version(t):
            continue
        if f"{m.group(1)}.{m.group(2)}.{m.group(3)}" != base:
            continue
        n = int(m.group(4)) if m.group(4) is not None else 0
        highest = n if highest is None else max(highest, n)
    return base if highest is None else f"{base}.{highest + 1}"


def render_section(version, date, prs):
    lines = [f"## {version} ({date.isoformat()})", ""]
    if prs:
        for pr in prs:
            lines.append(f"- {pr['title']} ([#{pr['number']}]({pr['url']}))")
    else:
        lines.append("- Maintenance release (no merged PRs).")
    return "\n".join(lines) + "\n"


def prepend_changelog(existing, section):
    """Insert the section after the header (before the first '## ' section)."""
    if not existing.strip():
        return CHANGELOG_HEADER + section
    idx = existing.find("\n## ")
    if idx == -1:
        return existing.rstrip("\n") + "\n\n" + section
    return existing[: idx + 1] + section + "\n" + existing[idx + 1:]


# --- git / gh plumbing ---

def run(*args, check=True):
    r = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, encoding="utf-8")
    if check and r.returncode != 0:
        raise SystemExit(f"command failed: {' '.join(args)}\n{r.stderr.strip()}")
    return r.stdout.strip()


def git(*args, check=True):
    return run("git", *args, check=check)


def calver_tags():
    return [t for t in git("tag", "--list").splitlines() if valid_version(t)]


def latest_tag(tags):
    def key(t):
        m = TAG_RE.match(t)
        return tuple(int(x or 0) for x in m.groups())
    return max(tags, key=key) if tags else None


def preflight(prev):
    problems = []
    if git("status", "--porcelain"):
        problems.append("working tree is dirty")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    if branch != "main":
        problems.append(f"not on main (on '{branch}')")
    git("fetch", "origin", "--tags", "--quiet")
    if branch == "main" and git("rev-parse", "HEAD") != git("rev-parse", "origin/main"):
        problems.append("local main is not equal to origin/main (pull/push first)")
    rng = f"{prev}..origin/main" if prev else "origin/main"
    if int(git("rev-list", "--count", rng)) == 0:
        problems.append(f"nothing new on main since {prev}")
    return problems


def merged_prs_since(prev):
    rng = f"{prev}..origin/main" if prev else "origin/main"
    shas = set(git("rev-list", rng).splitlines())
    out = run("gh", "pr", "list", "--repo", REPO, "--state", "merged", "--base", "main",
              "--limit", "1000", "--json", "number,title,url,mergeCommit,mergedAt")
    prs = [p for p in json.loads(out) if (p.get("mergeCommit") or {}).get("oid") in shas]
    prs.sort(key=lambda p: p["mergedAt"])
    return prs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--execute", action="store_true", help="apply (default is a dry-run)")
    ap.add_argument("--version", help="override the computed version (emergencies)")
    args = ap.parse_args()

    tags = calver_tags()
    prev = latest_tag(tags)
    today = datetime.date.today()
    if args.version:
        if not valid_version(args.version):
            raise SystemExit(f"--version {args.version!r} is not CalVer (YYYY.M.D[.N], no leading zeros)")
        if args.version in tags:
            raise SystemExit(f"tag {args.version} already exists")
        version = args.version
    else:
        version = next_version(tags, today)

    problems = preflight(prev)
    prs = merged_prs_since(prev)
    section = render_section(version, today, prs)

    print(f"Mode:             {'EXECUTE' if args.execute else 'dry-run'}")
    print(f"Previous tag:     {prev or '(none)'}")
    print(f"Next version:     {version}")
    print(f"PRs since tag:    {len(prs)}")
    print("\nChangelog section:\n")
    print(section)
    if problems:
        label = "REFUSING" if args.execute else "would refuse (fix before --execute)"
        for p in problems:
            print(f"{label}: {p}")
        sys.exit(1)
    if not args.execute:
        print("Dry-run only. Re-run with --execute to commit, tag, push and publish.")
        return

    existing = CHANGELOG.read_text(encoding="utf-8") if CHANGELOG.exists() else ""
    # newline="\n": LF on disk; core.autocrlf handles the checkout side.
    with open(CHANGELOG, "w", encoding="utf-8", newline="\n") as f:
        f.write(prepend_changelog(existing.replace("\r\n", "\n"), section))
    git("add", "CHANGELOG.md")
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8", newline="\n") as mf:
        mf.write(f"chore(release): {version}\n\n{CO_AUTHOR}\n")
    git("commit", "-F", mf.name)
    git("tag", "-a", version, "-m", f"Constructicon {version}")
    git("push", "origin", "main")
    git("push", "origin", version)
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8", newline="\n") as nf:
        nf.write(section.split("\n", 2)[2])  # notes = bullet list, without the heading
    run("gh", "release", "create", version, "--repo", REPO, "--title", version,
        "--notes-file", nf.name, "--verify-tag")
    print(f"Released {version}. Now run ./scripts/deploy.sh on the box.")


if __name__ == "__main__":
    main()
